title:        Alpha News Stream
url:          https://alpha-news-stream.github.io/portal/

permalink: /:categories/:year/:month/:day/:title/
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]

categories_path : /categories.html
tags_path : /tags.html

github_org: kinlane
github_repo: template-bootstrap
